### PR TITLE
Support running all tests from a specific path.

### PR DESCRIPTION
**Pull request by jgraham**
Previously when a path was supplied on the command line we tried to
manually convert this into a test url. Instead allow the manifest to
tell us all the tests that come from a specific path, since this is
the canonical source of truth here.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptrunner/242)

### CODE REVIEW

**Comment by jugglinmike** [comment]
This fix doesn't work when a path other than the current working directory is supplied via the `--tests` command-line argument. I believe the issue starts at [line 83](https://github.com/w3c/wptrunner/blob/a48459321f4a26a954059a2c5dc1590dca3181b5/wptrunner/manifestinclude.py#L83):

    maybe_path = os.path.join(os.path.abspath(os.curdir), url)

Because this assumes that translation from "url" to "filesystem" path is based on the current working directory, so [the subsequent invocation of `glob.glob` on line 94](https://github.com/w3c/wptrunner/blob/a48459321f4a26a954059a2c5dc1590dca3181b5/wptrunner/manifestinclude.py#L94) produces an empty array:

    paths = glob.glob(maybe_path)

This bug exists in `master`, but we may still want to address it in this patch since it effects the new functionality as well. What do you think?

**Comment by jgraham** [comment]
That seems as intended?

There are two expected modes of operation. Either you supply a test id i.e. the url of a test (e.g. `/dom/historical.html`) or you supply a path to a test relative to the current directory.

**Comment by jugglinmike** [comment]
That is not the behavior I am seeing. When the current working directory is one
directory above the `web-platform-tests/` directory, the following invocation
runs two tests:

    wptrunner --certutil-binary /usr/bin/certutil \
      --tests ./web-platform-tests/
      --metadata ./web-platform-tests/ \
      --product firefox \
      --binary /usr/bin/firefox-nightly \
      --prefs-root downloads/gecko-dev/testing/profiles \
      --webdriver-binary downloads/geckodriver \
      web-platform-tests/html/dom/self-origin.any.js

While the following does not run any tests:

    wptrunner --certutil-binary /usr/bin/certutil \
      --tests ./web-platform-tests/
      --metadata ./web-platform-tests/ \
      --product firefox \
      --binary /usr/bin/firefox-nightly \
      --prefs-root downloads/gecko-dev/testing/profiles \
      --webdriver-binary downloads/geckodriver \
      /html/dom/self-origin.any.js

I'm not sure how you define "test," though--maybe `self-origin.any.js` is not
technically a test, and thus not a candidate for specification via ID. I'm not
sure if that distinction will be expected by most users, though.

**Comment by jgraham** [comment]
Right, that's exactly it. You  either provide a path to a file or a test url. `/html/dom/self-origin.any.js` isn't a test url, so it doesn't run anything (the main use case for urls is copying from logs, so this doesn't come up in practice. Other than that I'm pretty sure that people always use the path to a file).

I suggest we change that in a followup if we decide it's important.

**Pull request merged**
