### PR TITLE
Add preliminary support for Safari 10

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptrunner/225)

### CODE REVIEW

**Comment by gsnedders** [comment]
I feel like we're getting more and more duplicated code across the Selenium-using executors. :(

**Comment by andreastt** [comment]
Also the inheritance surrounding overriding `WebDriverServer`’s ctor isn’t great, but this looks like a pretty low-impact change. I’m happy with it.

**Comment by andreastt** [comment]
I meant “low impact” as in “not dangerous” or controversial; not that having Safari support for WPT is. On the contrary: having that is excellent!

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/pull/8979; please continue all discussion there.

**Pull request closed without merging**
