### PR TITLE
Switch Tokenizer.tokenize to expect bytes, not text.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptrunner/216)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wptrunner/tests/test_testloader.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/wptrunner/216#-KUNWdhGwuXjDQQTpw3S:-KUNWdhJEEsVZQJ0DD0U:bpj27ib) ([raw file](https://github.com/w3c/wptrunner/blob/14c51d019e1739459df41bd6b51b016ed77cc835/wptrunner/tests/test_testloader.py#L21)):*
> ```Python
> structured.set_default_logger(structured.structuredlog.StructuredLogger("TestLoader"))
> 
> def test_filter_unicode():
> ```

The whitespace in this file is pretty weird.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/216)*

**Comment by Ms2ger** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[wptrunner/tests/test_testloader.py, line 21 at r1](https://reviewable.io:443/reviews/w3c/wptrunner/216#-KUNWdhGwuXjDQQTpw3S:-KUSdyUwIj3jdFJE76ZL:b-cowncx) ([raw file](https://github.com/w3c/wptrunner/blob/14c51d019e1739459df41bd6b51b016ed77cc835/wptrunner/tests/test_testloader.py#L21)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> The whitespace in this file is pretty weird.
</details>
So it was. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/216)*

**Comment by jgraham** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[wptrunner/tests/test_testloader.py, line 7 at r2](https://reviewable.io:443/reviews/w3c/wptrunner/216#-KUX4AXWheftlojD4296:-KUX4AXWheftlojD4297:bmygfp1) ([raw file](https://github.com/w3c/wptrunner/blob/bc377e96d04d2b8769791181cb21b1520c4a362e/wptrunner/tests/test_testloader.py#L7)):*
> ```Python
> from __future__ import unicode_literals
> 
> from mozlog import structured
> ```

In python `from` imports always go after `import` and stdlib imports are always first… Yeah rust is better here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/216)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/216)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/216)*

**Comment by jgraham** [comment]
Oh ffs, I obviously didn't actually want a merge. @Ms2ger mind force-pushing a rebase?

**Pull request merged**
