### PR TITLE
Remove logic for WebDriver session management

### PR DESCRIPTION
**Pull request by jugglinmike**
The tests for the WebDriver specification must themselves create and
destroy sessions. When the responsibility of session management is
assigned to wptrunner, such tests interfere with the execution of the
larger test suite.

Remove WebDriver session management logic from wptrunner and instead
expose the relevant information (i.e. the location of the running
WebDriver "remote end") via environment variables so that the tests may
assume this responsibility.

Remove corresponding Pytest "fixture" logic so that it may be maintained
in-line with the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptrunner/233)

### CODE REVIEW

**Comment by jugglinmike** [comment]
@jgraham Would you mind taking a look at this for me?

**Comment by jgraham** [comment]
Does this actually work? I would expect that the runner still starts a browser, and also that existing tests would be broken if they are now expected to start the browser manually.

**Comment by jugglinmike** [comment]
It does indeed work; you can verify by applying [the dependent patch to web-platform-tests](https://github.com/w3c/web-platform-tests/pull/4668), but I'm happy to explain why it works.

With these patches applied, we will no longer share the wdclient `Session` instance between the wptrunner and the tests themselves. The new contract is to simply specify the host and port of the WebDriver server. (This is in-line with our discussions on IRC to simplify the process of running the WebDriver tests without wptrunner.)

Because the tests create their own `Session` instances, the objects initially have a `None`-valied `session_id` attribute, which [causes them to issue a "New Session" command](https://github.com/w3c/wdclient/blob/97fcf19f9903ddb0d2d2564a6ef8d5320559c19d/webdriver/client.py#L14-L30) as part of the execution of the high-level instance methods (e.g. ["Get Title"](https://github.com/w3c/wdclient/blob/97fcf19f9903ddb0d2d2564a6ef8d5320559c19d/webdriver/client.py#L403-L406))..

In the absence of the `--connect-existing` flag, the geckodriver process responds to "New Session" commands by creating a new browser window. This is used by the test in question, and [the new `_session` "fixture" in web-platform-tests includes a "finalizer" that ends the session](https://github.com/w3c/web-platform-tests/pull/4668/files#diff-964146fac2fa5e4d1f03540fc56525ab), triggering the teardown of that window.

You are correct that wptrunner still provides a browser window. This is unused by the WebDriver tests. It's superfluous, but I believe we need to keep it around to support cases where WebDriver tests are run together with more "traditional" tests (which continue to rely on it).

**Comment by jgraham** [comment]
Well, not quite. Any existing window will be shut down at the end of each test type, so it's just a waste of resources to start it. We can probably fix this, but it requires refactoring the `browser_cls` bits in `wptrunner.py` so that we can have a different `Browser` per test type. Then wdspec` tests could use the `NullBrowser`. Do you want to try that or should I look at it in a followup?

**Comment by jugglinmike** [comment]
Thanks for the offer, but I think you've given me enough context to take a shot at it myself. I'll try to get something in place by the end of the day.

**Comment by jugglinmike** [comment]
@jgraham I've pushed up a commit that I believe addresses the problem. It seems
a little simplistic, though, so I could use your input.

Basically, because the `RemoteMarionetteProtocol` is *only* used by
`MarionetteWdspecExecutor`, I think we can safely ignore the provided `browser`
instance altogether. This means that it doesn't matter which class of `Browser`
it receives--`Firefox` or `NullBrowser`.

Does that sound right to you?

**Comment by jugglinmike** [comment]
> OK, assuming that you tested this and it works.

To be clear: I have only tested this with Firefox/Firefox Nightly and
GeckoDriver. I've reached out to a member of the Chromium team for more
information about the status of their browser, but it's my understanding that
FF/GeckoDriver is currently the only browser/WebDriver implementation that we
support. Is that right?

**Comment by jgraham** [comment]
Yeah, I think it will be easy to make this work with Chromedriver, but no one has put in the work yet.

**Comment by jugglinmike** [comment]
Okay, cool. I don't have commit rights to this repository (and am reluctant to land my own work besides), so can I trouble you to merge this?

**Comment by jugglinmike** [comment]
Thanks, James!

**Pull request merged**
