### PR TITLE
Implement support for running tests in Edge

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptrunner/153)

### CODE REVIEW

**Comment by gsnedders** [comment]
Edge should support *execute async script* as of Edge 20.10532 (the first stable release after that was 25.10586).

**Comment by jgraham** [comment]
So, critic is kind of broken here (I forgot @andreastt  had started a review), so maybe using https://reviewable.io/reviews/w3c/wptrunner/153#- is better in this case.

**Comment by andreastt** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[wptrunner/webdriver_server.py, line 48 \[r1\]](https://reviewable.io:443/reviews/w3c/wptrunner/153#-KN8QSs4HjF9hd4Rhskt:-KN8QSs50rFm_wU9wy_t:-244063012) ([raw file](https://github.com/w3c/wptrunner/blob/6cd3580a5745007e118c0996b8a0e0cf92864c52/wptrunner/webdriver_server.py#L48)):*
> ```Python
>         """Returns the full command for starting the server process as a list."""
> 
>     def start(self, block=False):
> ```

You need to update the users here, surely?

---

*[wptrunner/browsers/edge.py, line 48 \[r1\]](https://reviewable.io:443/reviews/w3c/wptrunner/153#-KN8Q_dQCg5i50CpvAma:-KN8Q_dRjwByPReVGrCN:2044522579) ([raw file](https://github.com/w3c/wptrunner/blob/6cd3580a5745007e118c0996b8a0e0cf92864c52/wptrunner/browsers/edge.py#L48)):*
> ```Python
>         Browser.__init__(self, logger)
>         self.server = EdgeDriverServer(self.logger, binary=webdriver_binary)
>         self.webdriver_host = "localhost"
> ```

This resolves fine on Windows?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/153)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[wptrunner/webdriver_server.py, line 48 \[r1\]](https://reviewable.io:443/reviews/w3c/wptrunner/153#-KN8QSs4HjF9hd4Rhskt:-KN8z-HRekAkjiHZHUUy:247154872) ([raw file](https://github.com/w3c/wptrunner/blob/6cd3580a5745007e118c0996b8a0e0cf92864c52/wptrunner/webdriver_server.py#L48)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> You need to update the users here, surely?
</details>
I don't see how it ever worked before tbh. But I guess I should check that the chrome backend still works.

---

*[wptrunner/browsers/edge.py, line 48 \[r1\]](https://reviewable.io:443/reviews/w3c/wptrunner/153#-KN8Q_dQCg5i50CpvAma:-KN8zAjWLkTAIbv-xH5t:-754957018) ([raw file](https://github.com/w3c/wptrunner/blob/6cd3580a5745007e118c0996b8a0e0cf92864c52/wptrunner/browsers/edge.py#L48)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> This resolves fine on Windows?
</details>
In fact it's mandatory to use `localhost`, using `127.0.0.1` produces an error for some reason that makes it clear it's an explicit design choice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/153)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wptrunner/webdriver_server.py, line 48 \[r1\]](https://reviewable.io:443/reviews/w3c/wptrunner/153#-KN8QSs4HjF9hd4Rhskt:-KNpnpwXeanNUv4bfew2:-1451853558) ([raw file](https://github.com/w3c/wptrunner/blob/6cd3580a5745007e118c0996b8a0e0cf92864c52/wptrunner/webdriver_server.py#L48)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I don't see how it ever worked before tbh. But I guess I should check that the chrome backend still works.
</details>
AFAICT this doesn't break anything and as I said, the previous default looks wrong to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptrunner/153)*

**Comment by andreastt** [comment]
LGTM

**Pull request merged**
